## The dataset

This is a real dataset and it was downloaded using web scraping techniques. The data contains registers from fotocasa which is one of the most popular websites of real estate in Spain. Please, do not do this (web scraping) unless it is for academic purposes.

The dataset was downloaded a few years ago by Henry Navarro and In no case were economic returns obtained from it.

It contains thousands of data from real homes published on the web www.fotocasa.com. Your goal is to extract as much information as possible with the knowledge you have so far about data science, for example what is the most expensive home in the entire dataset?

Let's start with precisely that question... Good luck!

#### Read the dataset assets/real_estate.csv and try to visualize the table (★☆☆)

In [ ]:
import pandas as pd
# this CSV file contains semicolons instead of comas as separator
ds = pd.read_csv('assets/real_estate.csv', sep=';')
ds

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,15331,153901377,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,96.0,259470,...,0,0,0,0,0,0,"40,45416","-3,70286",NaN,NaN
15331,15332,150394373,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,150.0,165000,...,0,0,0,0,0,0,"40,36652","-3,48951",NaN,NaN
15332,15333,153901397,False,tecnocasa torrelodones,912780348.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,175.0,495000,...,0,0,0,0,0,0,"40,57444","-3,92124",NaN,NaN
15333,15334,152607440,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,101.0,195000,...,0,0,0,0,0,0,"40,36967","-3,48105",NaN,NaN
15334,15335,153901356,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,152.0,765000,...,0,0,0,0,0,0,"40,45773","-3,69068",NaN,NaN

#### What is the most expensive home in the dataset? (★☆☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
most_expensive_home = ds.sort_values(by='price', ascending=False).iloc[0]


print(most_expensive_home)

:

#### What is cheapest home in the dataset? (★☆☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
cheapest_home = ds[ds['price'] > 0].sort_values(by='price').iloc[0]

print(cheapest_home)

#### What is the biggest and the smallest home in the dataset? (★☆☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
biggest_home = ds[ds['surface'] > 0].sort_values(by='surface', ascending=False).iloc[0]
smallest_home = ds[ds['surface'] > 0].sort_values(by='surface').iloc[0]

print(biggest_home)

print(smallest_home)

#### How many populations (level5) the dataset contains? (★☆☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
populations_count = ds['level5'].nunique()

print(populations_count)

#### Does the dataset contain NAs? (★☆☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
missing_values = ds.isna().sum()

print(missing_values)

#### Delete the NAs of the dataset, if applicable (★★☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
data_cleaned = ds.dropna()

print(data_cleaned)

#### What is the mean of prices in the population (level5) of "Arroyomolinos (Madrid)"? (★★☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
arroyomolinos_population = ds[ds['level5'] == "Arroyomolinos (Madrid)"]

mean_price_arroyomolinos = arroyomolinos_population['price'].mean()


print(mean_price_arroyomolinos)

#### Plot the histogram of prices for the population (level5) of "Arroyomolinos (Madrid)" and explain what you observe (★★☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
import matplotlib.pyplot as plt
import seaborn as sns

arroyomolinos_population = ds[ds['level5'] == "Arroyomolinos (Madrid)"]

plt.figure(figsize=(10, 6))
sns.histplot(arroyomolinos_population['price'], bins=20, kde=True)
plt.title("Histogram of Prices in Arroyomolinos (Madrid)")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()
 #### there are a few very expensive properties that bringthe average price higher.
 ####B y looking at  the histogram i can gain more of an insight into the price distribution for homes

#### Now let's work with the "south belt" of madrid. Make a subsetting that contains the following populations (level5): "Fuenlabrada","Leganés","Getafe","Alcorcón" (★★☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
south_belt_subset = ds[ds['level5'].isin(["Fuenlabrada", "Leganés", "Getafe", "Alcorcón"])]

print(south_belt_subset)

#### Make a bar plot of the median of prices (★★★)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
import matplotlib.pyplot as plt

south_belt_subset = ds[ds['level5'].isin(["Fuenlabrada", "Leganés", "Getafe", "Alcorcón"])]

median_prices = south_belt_subset.groupby('level5')['price'].median()


plt.figure(figsize=(10, 6))
median_prices.plot(kind='bar', color='skyblue')
plt.title("Median Prices in the South Belt of Madrid")
plt.xlabel("Population")
plt.ylabel("Median Price")
plt.xticks(rotation=45)  
plt.tight_layout()
plt.show()

#### Calculate the sample mean and variance of the variables: price, rooms, surface area and bathrooms (★★★)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
mean_price = ds['price'].mean()
variance_price = ds['price'].var()

mean_rooms = ds['rooms'].mean()
variance_rooms = ds['rooms'].var()

mean_surface = ds['surface'].mean()
variance_surface = ds['surface'].var()

mean_bathrooms = ds['bathrooms'].mean()
variance_bathrooms = ds['bathrooms'].var()


print("Sample Mean and Variance for Variables:")
print("Price - Mean:", mean_price, "Variance:", variance_price)
print("Rooms - Mean:", mean_rooms, "Variance:", variance_rooms)
print("Surface - Mean:", mean_surface, "Variance:", variance_surface)
print("Bathrooms - Mean:", mean_bathrooms, "Variance:", variance_bathrooms)

#### What is the most expensive home of each population? (★★☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
most_expensive_homes = ds.groupby('level5').apply(lambda x: x.loc[x['price'].idxmax()])

#im a bit confuse on waht the question was askng of me

#### Normalize the variable of prices for each population and plot the 4 histograms in the same plot (★★★)

In [ ]:
import pandas as pd

# Load the dataset
ds = pd.read_csv('assets/real_estate.csv', sep=';')

population_columns = ['level1', 'level2', 'level3', 'level4', 'level5', 'level6', 'level7', 'level8']
ds['population_identifier'] = ds[population_columns].apply(lambda x: '-'.join(x.astype(str)), axis=1)

unique_populations = ds['population_identifier'].unique()

most_expensive_homes = pd.DataFrame(columns=ds.columns)

for population in unique_populations:
    subset = ds[ds['population_identifier'] == population]
    most_expensive_home = subset.loc[subset['price'].idxmax()]
    most_expensive_homes = pd.concat([most_expensive_homes, most_expensive_home.to_frame().T])


most_expensive_homes.drop(columns=['population_identifier'], inplace=True)


most_expensive_homes.reset_index(drop=True, inplace=True)

print("Most Expensive Homes for Each Population")
print(most_expensive_homes)

#### Make a plot of the coordinates (lat and long) of the south belt of Madrid by color of each population (★★★★) 
This is a extremely hard exercise and we highly recommend to do it at the end of everything

In [ ]:
# Run in console the following command before run the rest of code:
# jupyter nbextension enable --py --sys-prefix ipyleaflet
from ipyleaflet import Map, basemaps

# Map centred on (60 degrees latitude et -2.2 degrees longitude)
# Latitude, longitude
map = Map(center = (60, -2.2), zoom = 2, min_zoom = 1, max_zoom = 20, 
    basemap=basemaps.Stamen.Terrain)
map

In [ ]:
## HERE: plot the coordinates of the estates
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
from ipyleaflet import Map, basemaps, Marker, CircleMarker
south_belt_populations = ["Fuenlabrada", "Leganés", "Getafe", "Alcorcón"]

madrid_map = Map(center=(40.4168, -3.7038), zoom=11, basemap=basemaps.Stamen.Terrain)
## PUT HERE YOUR CODE:

for population in south_belt_populations:
    subset = ds[ds['level5'] == population]
    for index, row in subset.iterrows():
        lat = float(row['latitude'].replace(',', '.'))  
        lon = float(row['longitude'].replace(',', '.'))  
        
        # Define the marker color based 
        if population == "Fuenlabrada":
            color = "red"
        elif population == "Leganés":
            color = "blue"
        elif population == "Getafe":
            color = "green"
        elif population == "Alcorcón":
            color = "purple"
        
       
        marker = CircleMarker(location=(lat, lon), color=color, radius=3)
        
        
        madrid_map.add_layer(marker)

# Display the map
#this toook forever to do >.<
madrid_map

#### What can you say about the price per square meter between the towns of Getafe and Alcorcón?

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
getafe_data = ds[ds['level5'] == "Getafe"]
alcorcon_data = ds[ds['level5'] == "Alcorcón"]

getafe_price_per_sqm = getafe_data['price'] / getafe_data['surface']
alcorcon_price_per_sqm = alcorcon_data['price'] / alcorcon_data['surface']

mean_price_per_sqm_getafe = getafe_price_per_sqm.mean()
mean_price_per_sqm_alcorcon = alcorcon_price_per_sqm.mean()


print("Mean Price Per Square Meter in Getafe:", mean_price_per_sqm_getafe)
print("Mean Price Per Square Meter in Alcorcón:", mean_price_per_sqm_alcorcon)
# Mean Price Per Square Meter in Getafe: 2066.314949251463
# Mean Price Per Square Meter in Alcorcón: 2239.302480199618

#### Reload the data, is the average of "Valdemorillo" and "Galapagar" prices the same?

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
valdemorillo_data = ds[ds['level5'] == "Valdemorillo"]
galapagar_data = ds[ds['level5'] == "Galapagar"]


average_price_valdemorillo = valdemorillo_data['price'].mean()
average_price_galapagar = galapagar_data['price'].mean()

# Displayingg esults
print("Average Price in Valdemorillo:", average_price_valdemorillo)
print("Average Price in Galapagar:", average_price_galapagar)

# Compareinggg  the averages
if average_price_valdemorillo == average_price_galapagar:
    print("The average prices in Valdemorillo and Galapagar are the same.")
else:
    print("The average prices in Valdemorillo and Galapagar are not the same.")

What happens if we do the same analysis for price/m2####  (★★☆)

In [ ]:
# gives you the average price that buyers are paying for each square meter of living space
#you can understand whether one town tends to have higher or lower property values on a per-square-meter basis
#a higher price/m2 could indicate a more liked areas while a lower price/m2 might suggest more affordable or spacious properties
#analyzing price/m2 trends over time can help identify changes in property values within specific areas

:

#### Could you say there is a relation between surface and price? (★★☆) 
Hint: make a scatter plot.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
ds = pd.read_csv('assets/real_estate.csv', sep=';')
plt.figure(figsize=(10, 6))
plt.scatter(ds['surface'], ds['price'], alpha=0.5)
plt.title("Scatter Plot of Surface Area vs. Price")
plt.xlabel("Surface Area (sqm)")
plt.ylabel("Price")
plt.grid(True)
plt.show()
print(ds)
#unable to see plot due to codesspace error

#### Make the same plot for 4 different populations (level5) and rearrange them on the same graph? (★★☆) 
Hint: make a scatter plot of each population using subplots.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
ds = pd.read_csv('assets/real_estate.csv', sep=';')

populations = ["Fuenlabrada", "Leganés", "Getafe", "Alcorcón"]  


fig, axs = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle("Scatter Plots of Surface Area vs. Price by Population", fontsize=16)

for i, population in enumerate(populations):
    row = i // 2
    col = i % 2
    ax = axs[row, col]
    
    
    population_data = ds[ds['level5'] == population]
    
 
    ax.scatter(population_data['surface'], population_data['price'], alpha=0.5)
    ax.set_title(f"Population: {population}")
    ax.set_xlabel("Surface Area (sqm)")
    ax.set_ylabel("Price")
    ax.grid(True)

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()
#unable to see plot due to codesspace error

In [ ]:
###How many  real estate agencies the dataset contains?

import pandas as pd


ds = pd.read_csv('assets/real_estate.csv', sep=';')

num_real_estate_agencies = ds['realEstate_name'].nunique()

print("Number of Unique Real Estate Agencies:", num_real_estate_agencies)

#### What is the population (level 5) that contains the most houses? (★★☆)

In [ ]:
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')

population_counts = ds['level5'].value_counts()


most_houses_population = population_counts.idxmax()
num_houses_most_population = population_counts.max()

#the results
print("Population with the Most Houses:", most_houses_population)
print("Number of Houses in the Most Populated Population:", num_houses_most_population)